### ISSUE TITLE
Selenate.InitWebDriver default IE Options cause some tests to fail

### ISSUE THREAD

**Issue by philspokas** [IntelliTect/TestTools#56]
Details are to be determined. But, the ideal solution is to provide over-ridable capabilities that can be driven by the tests.

**Comment by PandaMagnus** [comment]
@philspokas Any issues with me closing this due to people moving to Edge? Or should I actually try to figure out what happened here for legacy clients?

It was not my intention to wait this long, but since we're here... And also if Playwright gets more adoption, it's possible Selenium might get knocked off of its perch.

**Comment by philspokas** [comment]
I'm good with closing
